name: CD
on:
  release:
    types: [created]

jobs:
  release:
    name: Deploy Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        exclude:
          - os: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Hub already installed
        run: |
          hub --version
          echo "TAG" $TAG
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          # Optionally strip `v` prefix
          strip_v: true
      - name: Use tag
        run: |
          echo ${{steps.tag.outputs.tag}}
          export TAG=${{steps.tag.outputs.tag}}
          echo $TAG
      - name: Run hub commands
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cargo build --bin rust_mdb_load --release
          if [ "$RUNNER_OS" == "Linux" ]; then
              cd target/release
              export TAG=${{steps.tag.outputs.tag}}
              export ASSET="rust_mdb_load-$TAG-linux-x86_64.tar.gz"
              tar czf ../../$ASSET rust_mdb_load
          elif [ "$RUNNER_OS" == "macOS" ]; then
              cd target/release
              export TAG=${{steps.tag.outputs.tag}}
              export ASSET="rust_mdb_load-$TAG-osx-x86_64.tar.gz"
              sudo /usr/sbin/purge
              tar czf ../../$ASSET rust_mdb_load
          fi
          cd ../..
          hub release edit -m "" --attach $ASSET $TAG
          

#          elif [ "$RUNNER_OS" == "Windows" ]; then
#              asset="rust_mdb_load-$TAG-$host.zip"
#              7z a ../../$ASSET rust_mdb_load.exe

#      - name: Build and deploy artifacts
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: ci/make-release.sh ${{ matrix.os }}
#        shell: bash
